packaging_format = 2

id = "osp"
name = "Open Streaming Platform"
description.en = "Explain in *a few (10~15) words* the purpose of the app or what it actually does (it is meant to give a rough idea to users browsing a catalog of 100+ apps)"
description.fr = "Expliquez en *quelques* (10~15) mots l'utilité de l'app ou ce qu'elle fait (l'objectif est de donner une idée grossière pour des utilisateurs qui naviguent dans un catalogue de 100+ apps)"

version = "0.9.10~ynh1"

maintainers = [""]

[upstream]
license = "MIT"
website = "https://openstreamingplatform.com/"
demo = "https://demo.openstreamingplatform.com/"
admindoc = "https://wiki.openstreamingplatform.com"
userdoc = "https://yunohost.org/apps"
code = "https://gitlab.com/Deamos/flask-nginx-rtmp-manager"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/osp"

    [install.admin]
    type = "user"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en"]
    default = "fr"

    [install.password]
    help.en = "Use the help field to add an information for the admin about this question."
    help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
    type = "password"

[resources]
        [resources.sources.main]
        url = "https://gitlab.com/osp-group/flask-nginx-rtmp-manager/-/archive/0.9.10/flask-nginx-rtmp-manager-0.9.10.tar.gz"
        sha256 = "b4d00ce27b1614a3250334ddab5f372c3c38e0fac4cfd034f65b16f3d92e7e58"


    [resources.system_user]

    [resources.install_dir]

    [resources.ports]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, ffmpeg, build-essential, libpcre3, libpcre3-dev, libssl-dev, gunicorn3, uwsgi-plugin-python"

    [resources.database]
    type = "mysql"
